/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.SignalController;
import java.awt.Graphics;
import javax.swing.JTextArea;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author adkm2
 */
public class InputForm extends javax.swing.JFrame {
    private SignalController controller = new SignalController();
    /**
     * Creates new form InputForm
     */
    public InputForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Line Coding");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputLabel = new javax.swing.JLabel();
        titleLabel = new java.awt.Label();
        manchesterBtn = new javax.swing.JButton();
        nrzBtn1 = new javax.swing.JButton();
        digitalLabel = new java.awt.Label();
        modulationLabel = new java.awt.Label();
        FrequencyBtn = new javax.swing.JButton();
        AmplitudeBtn = new javax.swing.JButton();
        PhaseBtn = new javax.swing.JButton();
        seeBinBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        inputLabel.setText("Enter text (ASCII/UTF-8):");

        titleLabel.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        titleLabel.setName("LINE CODING"); // NOI18N
        titleLabel.setText("LINE CODING");

        manchesterBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        manchesterBtn.setText("Manchester");
        manchesterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manchesterBtnActionPerformed(evt);
            }
        });

        nrzBtn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nrzBtn1.setText("NRZ");
        nrzBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nrzBtn1ActionPerformed(evt);
            }
        });

        digitalLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        digitalLabel.setForeground(new java.awt.Color(102, 102, 102));
        digitalLabel.setName(""); // NOI18N
        digitalLabel.setText("Digital Signal:");

        modulationLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        modulationLabel.setForeground(new java.awt.Color(102, 102, 102));
        modulationLabel.setText("Modulation:");

        FrequencyBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        FrequencyBtn.setText("Frequency");
        FrequencyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrequencyBtnActionPerformed(evt);
            }
        });

        AmplitudeBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AmplitudeBtn.setText("Amplitude");
        AmplitudeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmplitudeBtnActionPerformed(evt);
            }
        });

        PhaseBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        PhaseBtn.setText("Phase");
        PhaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhaseBtnActionPerformed(evt);
            }
        });

        seeBinBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seeBinBtn.setText("See Binary");
        seeBinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeBinBtnActionPerformed(evt);
            }
        });

        inputText.setBackground(new java.awt.Color(255, 255, 255));
        inputText.setColumns(20);
        inputText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inputText.setForeground(new java.awt.Color(51, 51, 51));
        inputText.setLineWrap(true);
        inputText.setRows(5);
        inputText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(inputText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nrzBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(digitalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manchesterBtn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(seeBinBtn))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PhaseBtn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AmplitudeBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(FrequencyBtn))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(inputLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(modulationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(digitalLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seeBinBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nrzBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manchesterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modulationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FrequencyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AmplitudeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PhaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nrzBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nrzBtn1ActionPerformed
        // TODO add your handling code here:
        String text = inputText.getText();
        controller.showNRZ(controller.signalEncoder(text));
    }//GEN-LAST:event_nrzBtn1ActionPerformed

    private void manchesterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manchesterBtnActionPerformed
        // TODO add your handling code here:
        String text = inputText.getText();
        controller.showManchester(controller.signalEncoder(text));
    }//GEN-LAST:event_manchesterBtnActionPerformed

    private void FrequencyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrequencyBtnActionPerformed
        // TODO add your handling code here:
        String text = inputText.getText();
        controller.showFrequency(controller.signalEncoder(text));
    }//GEN-LAST:event_FrequencyBtnActionPerformed

    private void AmplitudeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmplitudeBtnActionPerformed
        // TODO add your handling code here:
        String text = inputText.getText();
        controller.showAmplitude(controller.signalEncoder(text));
    }//GEN-LAST:event_AmplitudeBtnActionPerformed

    private void PhaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhaseBtnActionPerformed
        // TODO add your handling code here:
        String text = inputText.getText();
        controller.showPhase(controller.signalEncoder(text));
    }//GEN-LAST:event_PhaseBtnActionPerformed

    private void seeBinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeBinBtnActionPerformed
        String text = inputText.getText();
        
        JTextArea ta = new JTextArea(controller.stringBits(text));
        ta.setEditable(false);
        ta.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 16));
        ta.setLineWrap(true);
        ta.setWrapStyleWord(true);
        
        JScrollPane sc = new JScrollPane(ta, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        sc.setPreferredSize(new Dimension(450, 350));
        
        JOptionPane.showMessageDialog(this, sc, "Binary of the text", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_seeBinBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AmplitudeBtn;
    private javax.swing.JButton FrequencyBtn;
    private javax.swing.JButton PhaseBtn;
    private java.awt.Label digitalLabel;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JTextArea inputText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manchesterBtn;
    private java.awt.Label modulationLabel;
    private javax.swing.JButton nrzBtn1;
    private javax.swing.JButton seeBinBtn;
    private java.awt.Label titleLabel;
    // End of variables declaration//GEN-END:variables
}
